### ISSUE TITLE
java.lang.ClassCastException in ProblemTextExtractor.java

### ISSUE THREAD

**Issue by medboz** [JetBrains/teamcity-investigations-auto-assigner#19]
Hi,

The plugin throws the following exception(I've added a try catch in processBrokenBuildsOneThread() method to see it):
```
[2018-08-16 11:31:24,336]  ERROR [uto-Assigner- 1] - TestAndBuildProblemsDispatcher - Error occurred when processing builds from 'myFailedBuilds':java.lang.ClassCastException: jetbrains.buildServer.serverSide.buildLog.BuildLogFactory$RunningAwareBuildLog cannot be cast to jetbrains.buildServer.serverSide.SBuild
	at jetbrains.buildServer.iaa.utils.ProblemTextExtractor.getBuildProblemText(ProblemTextExtractor.java:43)
	at jetbrains.buildServer.iaa.heuristics.BrokenFileHeuristic.findResponsibleUser(BrokenFileHeuristic.java:83)
	at jetbrains.buildServer.iaa.processing.ResponsibleUserFinder.findResponsibleUser(ResponsibleUserFinder.java:48)
	at jetbrains.buildServer.iaa.processing.FailedTestAndBuildProblemsProcessor.processBuild(FailedTestAndBuildProblemsProcessor.java:84)
	at jetbrains.buildServer.iaa.FailedTestAndBuildProblemsDispatcher.processBrokenBuild(FailedTestAndBuildProblemsDispatcher.java:96)
	at jetbrains.buildServer.iaa.FailedTestAndBuildProblemsDispatcher.processBrokenBuildsOneThread(FailedTestAndBuildProblemsDispatcher.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at jetbrains.buildServer.util.executors.TeamCityScheduledThreadPoolExecutor$RunnableScheduledFutureWrapper.run(TeamCityScheduledThreadPoolExecutor.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
 
```
I think, the cause is the cast ` (SBuild)build.getBuildLog()` in this line:
```
final List<LogMessage> errors =
          new BuildLogCompileErrorCollector().collectCompileErrors(compileBlockIndex, (SBuild)build.getBuildLog());
```

Could you please fix it if you confirm it's the source cause of this error?

**Comment by rugpanov** [comment]
@medboz , thank you for your report. 
I try to fix this ASAP.

**Comment by rugpanov** [comment]
@medboz , in the [last build](https://teamcity.jetbrains.com/viewLog.html?buildId=1569526&buildTypeId=TeamCityPluginsByJetBrains_InvestigationsAutoAssigner_BuildAgainstTeamCity81x&tab=artifacts) the problem was fixed. Thank you for your help.

**Comment by medboz** [comment]
Perfect, thank you :)
